sudo: required # super user level permissions
services:
  - docker # docker cli pre-installed

# series of commands before our test are run
before_install:
  - docker build -f Dockerfile.dev -t b2o5t/react-ts .

# commands to run test suits
# CI=true allow run the test and exit from the image once the tests are completed
script:
  - docker run -e CI=true b2o5t/react-ts yarn test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
  region: 'us-east-2'
  app: 'docker-react-ts'
  env: 'DockerReactTs-env'
  bucket_name: 'elasticbeanstalk-us-east-2-944179170239'
  # bucket_path: docker-react-ts # by default path is equal app name
  on:
    branch: master # every time deploy when there is new code in master
